### ISSUE TITLE
Make sure all the flows in the sample at least handle no HTTP connection

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin.exposurenotification#15]
The internet might go down, or might be in an area for no connectivity.

 - submitting
    - the user should submit from a subway station in the heart of Africa
 - getting things
    - the status for "I've fetched" should only be set when we know we got them all

**Comment by Redth** [comment]
I think we're ok on the 'getting things'.

We might want to do something more on the submitting of things, but I think we're probably safe for now there too.  Only 14 keys need to be submitted this is a pretty small payload and wouldn't require a lot of data like we originally thought it might.  Closing for now.
