### ISSUE TITLE
[Cross Platform Exposure Notification] Overall status of ExposureNotification on iOS

### ISSUE THREAD

**Issue by ncpavels** [xamarin/xamarin.exposurenotification#37]
Hello,

In the current implementation of the cross-platform Xamarin Exposure Notification API it is not possible to keep track of overall status of ExposureNotification on iOS devices. 

For the native implementation of ExposureNotification it is suggested to use KVO to monitor changes of **ENStatus** variable in **ENManager** ([docs](https://developer.apple.com/documentation/exposurenotification/enmanager/3583724-exposurenotificationstatus)). 
Checking the ENStatus allows developers to react correspondingly in the situation when ExposureNotification is authorised by user, but Bluetooth is turned off. In this case, an instance property **exposureNotificationStatus** will be set to **[case .bluetoothOff](https://developer.apple.com/documentation/exposurenotification/enstatus/bluetoothoff)** which allows app to act correspondingly. 

The only way to get the status of scanning in the current cross-platform Xamarin Exposure Notification API is to call `Xamarin.ExposureNotifications.ExposureNotification.IsEnabledAsync()`. Using this method might not be sufficient due to simply returning boolean value and additional checks to identify the reason for why scanning might not be working are required. 

I was wondering would Xamarin.ExposureNotification dev team consider adding this functionality to the cross-platform Xamarin Exposure Notification API? Or is it intended that app developers who want to use cross-platform Xamarin Exposure Notification API create their own bindings to ENManager to monitor the status of ExposureNotification on iOS devices. 

Thank you.

**Comment by Redth** [comment]
Can you provide a bit more context on how you would use this in an implementation?

I guess I'm wondering if we can do something more useful than just exposing an event when the status changes.  Eg: are you intending to pop up a local notification if bluetooth or exposure notifications get turned off?

**Comment by ncpavels** [comment]
Yes, this is exactly the use case.

We are interested in updating the UI correspondingly when the scanning might be off due to different conditions. 

For example, the Exposure Logging might be turned on in Settings, but the Bluetooth is turned off. In this case, it would be great to let user know that the scanning if off for that very reason, and prompt a local notification for turning Bluetooth on (or at least update the UI to reflect the status of Bluetooth). Since other Bluetooth functionality is not permitted by Apple apart from the one that is provided by Exposure Notification API, we do not see how we could have used, for example, Core Bluetooth API for this purpose.

And then there are other cases, like when Bluetooth is on, but the user has disabled the Exposure Logging in Settings. This would then reflect in another UI update.

Another case could be where the user might have both Exposure Logging and Bluetooth turned on, but the scanning is disabled in the app with `Xamarin.ExposureNotifications.ExposureNotification.StopAsync()`. Perhaps, this should be treated differently from the previous two.

I guess exposing the event would work fine for this purpose. But if anyone else comes up with more scenarios how this ENStatus could be used we would like to hear them.

Thank you!

**Comment by Redth** [comment]
@ncpavels we have just landed a new cross platform api for this: `GetStatusAsync()`.  On Android it will really only return `BluetoothOff`, `Disabled`, or `Active`, but on iOS more of the cross platform enum's statuses will be possible.

This is also available on nuget now as of  [0.3.0-preview](https://www.nuget.org/packages/Xamarin.ExposureNotification/0.3.0-preview)

Please open a new issue if you have any more requests/concerns/feedback, thanks!
