### ISSUE TITLE
Missing fields in ExposureDetectionSummary and ExposureConfiguration

### ISSUE THREAD

**Issue by TMHolen95** [xamarin/xamarin.exposurenotification#40]
Hi, the current implementation of ExposureDetectionSummary is missing fields for: AttenuationDurations. Note that the Apple API has extra data under the metadata for this class.

In addition, the implementation of ExposureConfiguration is missing:
durationAtAttenuationThresholds. The ExposureConfiguration parameter durationAtAttenuationThresholds is present in the
[Google documentation](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf). 

Do note that in the Apple documentation for the ExposureConfiguration durationAtAttenuationThresholds is contained within the Metadata, under the key
["attenuationDurationThresholds"](https://developer.apple.com/documentation/exposurenotification/enexposureconfiguration/3586322-metadata)

**Comment by Redth** [comment]
Thanks @TMHolen95 !

This one snuck by.  I think #41 should take care of this.  One thing I'm uncertain is if setting `int[]` to the `NSDictionary` is the right thing here, but the docs are pretty unclear.

**Comment by Redth** [comment]
This should be good to go.  All nuget packages contain this now.
