### ISSUE TITLE
Init() is not working on iOS due to Xamarin.iOS bug in current stable release.

### ISSUE THREAD

**Issue by pavshr** [xamarin/xamarin.exposurenotification#44]
Hello,

I was investigating the functionality of `Init()` API on iOS using cross-platform Xamarin.ExposureNotification library, and see that it does not work as it is intended to.

During my tests, I discovered that the background task is not scheduled at all and in fact is never called from the background. It basically means that `UpdateKeysFromServer()`, which is perhaps one of the most important APIs that allows to detect exposures regularly, is not called from background. In our project, we call `Xamarin.ExposureNotifications.ExposureNotification.Init()` from the AppDelegate's `FinishedLaunching()` method.

So I implemented the scheduling task myself, the same way it is done by you guys in the `Init()` API but without `PlatformIsEnabled()` check and with hardcoded task ID for our project (bundle id + ".exposure-notification"). I did it to secure that the task would be registered by **BGTaskScheduler** and executed by iOS not depending on any conditions.

By doing this, finally, I spotted in VS debug console the execution of the task from the background. However, it failed with an exception with the following error message:

> Cannot create an instance of BackgroundTasks.BGTask because it is an abstract class

Further search led me to this issue in Xamarin.iOS project: https://github.com/xamarin/xamarin-macios/issues/7456 

As I see it, the way I implemented the task by reflecting how it is done in the cross-platform Xamarin.ExposureNotification library will not work due to the bug in current Xamarin.iOS release. Which means that until the fix https://github.com/xamarin/xamarin-macios/commit/c2a220d84e92d95a3c09af186e4a30264d78d886 appears in the stable, or at least the next preview release, the task will not be properly scheduled and executed in the background using the new iOS 13 [BGTaskScheduler](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler). 

I would really like to hear some thoughts about this issue from Xamarin.ExposureNotification dev team. The way I see it at the moment, it is not possible to release Xamarin.ExposureNotification library without coordination with the Xamarin.iOS release that will include the fix https://github.com/xamarin/xamarin-macios/commit/c2a220d84e92d95a3c09af186e4a30264d78d886. It looks also that it is not possible to implement a workaround using deprecated API as proposed in https://github.com/xamarin/xamarin-macios/issues/7456#issuecomment-623690818 by @brminnick since we need to do it iOS 13 way via BGTaskScheduler in order to specify the id of the task. And this is the desired way to schedule the task in the background because only this way iOS ensures priority and more time for execution when executing this task:

> The BackgroundTask framework detects apps that contain the Exposure Notification entitlement and a background task that ends in exposure-notification. The operating system automatically launches these apps when they aren’t running and guarantees them more background time to ensure that the app can test and report results promptly.

src: https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure 

Thank you!

**Comment by brminnick** [comment]
@mandel-macaque Do you know which version of Xamarin.iOS does/will include the bug fix for `BGTask`?

**Comment by dalexsoto** [comment]
Hello @pavshr and @brminnick the [fix you are looking](https://github.com/xamarin/xamarin-macios/pull/8532) for is included in our vNext builds of Xamarin.iOS at the moment you would need a build from our [d16-7](https://github.com/xamarin/xamarin-macios/commits/d16-7) the following come from today's HEAD in order to unblock you:

-[xamarin.ios-13.20.1.2.pkg]( https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-7/bb5a3d353a647278d74e1db4d4d52aaa049ca7b9/27/package/notarized/xamarin.ios-13.20.1.2.pkg)
- [xamarin.mac-6.20.1.2.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-7/bb5a3d353a647278d74e1db4d4d52aaa049ca7b9/27/package/notarized/xamarin.mac-6.20.1.2.pkg)

**Comment by pavshr** [comment]
Thank you, much appreciated 👍

**Comment by dalexsoto** [comment]
Hello @pavshr and @brminnick, we have new candidate builds based on our current stable d16-6 + the needed fix and you can find them here

* [xamarin.ios-13.18.2.1.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-6/29c4ea73109b377a71866c53a6d43033d5c5e90b/49/package/notarized/xamarin.ios-13.18.2.1.pkg)
* [xamarin.mac-6.18.2.1.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-6/29c4ea73109b377a71866c53a6d43033d5c5e90b/49/package/notarized/xamarin.mac-6.18.2.1.pkg)

Please let us know if these works for you.

**Comment by Redth** [comment]
Closing this as we have a workaround, and a plan.  Thanks all!

**Comment by brminnick** [comment]
FYI - this fix is now available in the current Preview Channel in Xamarin.iOS v13.20.0.22

**Comment by dalexsoto** [comment]
@brminnick This is also included in the current released stable channel Xamarin.iOS 13.18.2.1 in both windows and Mac

**Comment by pavshr** [comment]
Yes, thank you again, we are now using stable release 13.18.2.1 to build and iOS 13 BGScheduling is not an issue anymore.
