### ISSUE TITLE
ExposureConfigurations are failing when detectingExposures

### ISSUE THREAD

**Issue by TMHolen95** [xamarin/xamarin.exposurenotification#62]
Hello @Redth , we are encountering problems we believe are connected to the Configuration. After we connected the code to our server and managed to retrieve files from it, we encountered stack traces that suggest there are problems with the ExposureConfigurations. 

Exceptions are thrown when we run:
await Xamarin.ExposureNotifications.ExposureNotification.UpdateKeysFromServer();

In the android part we do think the first line before the stack trace is quite relevant to the problem as it may suggest the configuration mapping is failing somewhere:
> [monodroid-assembly] typemap: unable to find mapping to a managed type from Java type 'com/google/android/gms/tasks/zzu' 
It is possible to inspect the zzu file in Android Studio but it is kind of obfuscated and is a class that extends Task<TResult>.  

Hit shift twice in Android Studio and search "com/google/android/gms/tasks/zzu" to see it

On Android we are receiving this stack trace:
>```
> Android.Gms.Common.Apis.ApiException: 10: Invalid file content: {ParcelFileDescriptor: java.io.FileDescriptor@1ef46ee}
>   at Xamarin.ExposureNotifications.ExposureNotification.PlatformDetectExposuresAsync (System.Collections.Generic.IEnumerable`1[T] keyFiles, System.Threading.CancellationToken cancellationToken) [0x000ea] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.android.cs:168 
>   at Xamarin.ExposureNotifications.ExposureNotification+<>c__DisplayClass13_0.<UpdateKeysFromServer>b__0 (System.Collections.Generic.IEnumerable`1[T] downloadedFiles) [0x001c4] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:115 
>   at NDB.Covid19.Base.AppleGoogle.ExposureNotification.ExposureNotificationHandler.FetchExposureKeyBatchFilesFromServerAsync (System.Func`2[T,TResult] submitBatches, System.Threading.CancellationToken cancellationToken) [0x0042c] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ExposureNotification/ExposureNotificationHandler.cs:177 
>   at Xamarin.ExposureNotifications.ExposureNotification.UpdateKeysFromServer (System.Threading.CancellationToken cancellationToken) [0x0006d] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:88 
>   at NDB.Covid19.Base.AppleGoogle.ViewModels.ENDeveloperToolsViewModel.PullKeysFromServer () [0x0002c] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ViewModels/ENDeveloperToolsViewModel.cs:110 
>   --- End of managed Android.Gms.Common.Apis.ApiException stack trace ---
> com.google.android.gms.common.api.ApiException: 10: Invalid file content: {ParcelFileDescriptor: java.io.FileDescriptor@1ef46ee}
> 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.1.0:6)
> 	at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@17.1.0:2)
> 	at com.google.android.gms.internal.nearby.zzae.onResult(com.google.android.gms:play-services-nearby@@18.0.2-eap:2)
> 	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.dispatchTransaction(com.google.android.gms:play-services-base@@17.1.0:11)
> 	at com.google.android.gms.internal.base.zaa.onTransact(com.google.android.gms:play-services-base@@17.1.0:13)
> 	at android.os.Binder.execTransact(Binder.java:735)
>```
I believe the [issue I created a few days ago](https://github.com/xamarin/xamarin.exposurenotification/issues/40) is related as it is referring to the variable that was previously missing attenuationDurationThresholds. The main takeaway from the stack trace below seems to be this:
> this class is not key value coding-compliant for the key attenuationDurationThresholds

On iOS we are receiving this stack trace:

> ```
> Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSUnknownKeyException Reason: [<__NSFrozenDictionaryM 0x282e3e340> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key attenuationDurationThresholds.
> Native stack trace:
> 	0   CoreFoundation                      0x00000001bd2787a8 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 1222568
> 	1   libobjc.A.dylib                     0x00000001bcf9abcc objc_exception_throw + 56
> 	2   CoreFoundation                      0x00000001bd17da58 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 195160
> 	3   Foundation                          0x00000001bd55e50c C82F8A4F-3D0F-33DB-8D40-C1E8BEF27E56 + 206092
> 	4   NDB.Covid19.iOS.AppleAPI            0x00000001014b0000 NDB.Covid19.iOS.AppleAPI + 5111808
> 	5   NDB.Covid19.iOS.AppleAPI            0x000000010147bf98 NDB.Covid19.iOS.AppleAPI + 4898712
> 	6   NDB.Covid19.iOS.AppleAPI            0x00000001024c2188 NDB.Covid19.iOS.AppleAPI + 21963144
> 	7   NDB.Covid19.iOS.AppleAPI            0x00000001011a144c NDB.Covid19.iOS.AppleAPI + 1905740
> 	8   NDB.Covid19.iOS.AppleAPI            0x0000000101127efc NDB.Covid19.iOS.AppleAPI + 1408764
> 	9   NDB.Covid19.iOS.AppleAPI            0x0000000101127cfc NDB.Covid19.iOS.AppleAPI + 1408252
> 	10  NDB.Covid19.iOS.AppleAPI            0x00000001011a1308 NDB.Covid19.iOS.AppleAPI + 1905416
> 	11  NDB.Covid19.iOS.AppleAPI            0x0000000101144228 NDB.Covid19.iOS.AppleAPI + 1524264
> 	12  NDB.Covid19.iOS.AppleAPI            0x0000000101477dbc NDB.Covid19.iOS.AppleAPI + 4881852
> 	13  NDB.Covid19.iOS.AppleAPI            0x000000010138e770 NDB.Covid19.iOS.AppleAPI + 3925872
> 	14  NDB.Covid19.iOS.AppleAPI            0x00000001025c0f80 mono_pmip + 28148
> 	15  NDB.Covid19.iOS.AppleAPI            0x000000010267c45c mono_pmip + 795344
> 	16  NDB.Covid19.iOS.AppleAPI            0x000000010267fcc0 mono_pmip + 809780
> 	17  NDB.Covid19.iOS.AppleAPI            0x0000000100fd54c0 NDB.Covid19.iOS.AppleAPI + 21696
> 	18  NDB.Covid19.iOS.AppleAPI            0x0000000100fdf230 NDB.Covid19.iOS.AppleAPI + 62000
> 	19  Foundation                          0x00000001bd662f78 C82F8A4F-3D0F-33DB-8D40-C1E8BEF27E56 + 1273720
> 	20  CoreFoundation                      0x00000001bd1f6c18 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 691224
> 	21  CoreFoundation                      0x00000001bd1f6b70 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 691056
> 	22  CoreFoundation                      0x00000001bd1f62f8 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 688888
> 	23  CoreFoundation                      0x00000001bd1f1328 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 668456
> 	24  CoreFoundation                      0x00000001bd1f0ce8 CFRunLoopRunSpecific + 424
> 	25  GraphicsServices                    0x00000001c733b38c GSEventRunModal + 160
> 	26  UIKitCore                           0x00000001c131f444 UIApplicationMain + 1932
> 	27  NDB.Covid19.iOS.AppleAPI            0x00000001014b9118 NDB.Covid19.iOS.AppleAPI + 5148952
> 	28  NDB.Covid19.iOS.AppleAPI            0x0000000101458bc0 NDB.Covid19.iOS.AppleAPI + 4754368
> 	29  NDB.Covid19.iOS.AppleAPI            0x0000000101458b44 NDB.Covid19.iOS.AppleAPI + 4754244
> 	30  NDB.Covid19.iOS.AppleAPI            0x0000000100ff2c04 NDB.Covid19.iOS.AppleAPI + 142340
> 	31  NDB.Covid19.iOS.AppleAPI            0x000000010138e770 NDB.Covid19.iOS.AppleAPI + 3925872
> 	32  NDB.Covid19.iOS.AppleAPI            0x00000001025c0f80 mono_pmip + 28148
> 	33  NDB.Covid19.iOS.AppleAPI            0x000000010267c45c mono_pmip + 795344
> 	34  NDB.Covid19.iOS.AppleAPI            0x00000001026826b4 mono_pmip + 820520
> 	35  NDB.Covid19.iOS.AppleAPI            0x000000010259f538 NDB.Covid19.iOS.AppleAPI + 22869304
> 	36  NDB.Covid19.iOS.AppleAPI            0x000000010275f020 _Z9__isctypeim + 62652
> 	37  NDB.Covid19.iOS.AppleAPI            0x0000000100febf84 NDB.Covid19.iOS.AppleAPI + 114564
> 	38  libdyld.dylib                       0x00000001bd0788f0 90BD401C-9E8F-354E-A74F-D4C152DEB1D8 + 6384
> 
>   at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:406 
>   at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
>   at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
>   at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
>   at Foundation.NSObject.SetValueForKey (Foundation.NSObject value, Foundation.NSString key) [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/NSObject.g.cs:547 
>   at Xamarin.ExposureNotifications.ExposureNotification.GetConfigurationAsync () [0x001dd] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.ios.cs:54 
>   at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr(intptr,intptr,intptr,intptr)
>   at Foundation.NSObject.SetValueForKey (Foundation.NSObject value, Foundation.NSString key) [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/NSObject.g.cs:547 
>   at Xamarin.ExposureNotifications.ExposureNotification.GetConfigurationAsync () [0x001dd] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.ios.cs:54 
>   at Xamarin.ExposureNotifications.ExposureNotification.PlatformDetectExposuresAsync (System.Collections.Generic.IEnumerable`1[T] keyFiles, System.Threading.CancellationToken cancellationToken) [0x0003c] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.ios.cs:157 
>   at Xamarin.ExposureNotifications.ExposureNotification+<>c__DisplayClass13_0.<UpdateKeysFromServer>b__0 (System.Collections.Generic.IEnumerable`1[T] downloadedFiles) [0x001d0] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:108 
>   at NDB.Covid19.Base.AppleGoogle.ExposureNotification.ExposureNotificationHandler.FetchExposureKeyBatchFilesFromServerAsync (System.Func`2[T,TResult] submitBatches, System.Threading.CancellationToken cancellationToken) [0x0051e] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ExposureNotification/ExposureNotificationHandler.cs:177 
>   at Xamarin.ExposureNotifications.ExposureNotification.UpdateKeysFromServer (System.Threading.CancellationToken cancellationToken) [0x0006d] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:88 
>   at NDB.Covid19.Base.AppleGoogle.ViewModels.ENDeveloperToolsViewModel.PullKeysFromServer () [0x0002c] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ViewModels/ENDeveloperToolsViewModel.cs:110 	0   CoreFoundation                      0x00000001bd2787a8 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 1222568
> 	1   libobjc.A.dylib                     0x00000001bcf9abcc objc_exception_throw + 56
> 	2   CoreFoundation                      0x00000001bd17da58 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 195160
> 	3   Foundation                          0x00000001bd55e50c C82F8A4F-3D0F-33DB-8D40-C1E8BEF27E56 + 206092
> 	4   NDB.Covid19.iOS.AppleAPI            0x00000001014b0000 NDB.Covid19.iOS.AppleAPI + 5111808
> 	5   NDB.Covid19.iOS.AppleAPI            0x000000010147bf98 NDB.Covid19.iOS.AppleAPI + 4898712
> 	6   NDB.Covid19.iOS.AppleAPI            0x00000001024c2188 NDB.Covid19.iOS.AppleAPI + 21963144
> 	7   NDB.Covid19.iOS.AppleAPI            0x00000001011a144c NDB.Covid19.iOS.AppleAPI + 1905740
> 	8   NDB.Covid19.iOS.AppleAPI            0x0000000101127efc NDB.Covid19.iOS.AppleAPI + 1408764
> 	9   NDB.Covid19.iOS.AppleAPI            0x0000000101127cfc NDB.Covid19.iOS.AppleAPI + 1408252
> 	10  NDB.Covid19.iOS.AppleAPI            0x00000001011a1308 NDB.Covid19.iOS.AppleAPI + 1905416
> 	11  NDB.Covid19.iOS.AppleAPI            0x0000000101144228 NDB.Covid19.iOS.AppleAPI + 1524264
> 	12  NDB.Covid19.iOS.AppleAPI            0x0000000101477dbc NDB.Covid19.iOS.AppleAPI + 4881852
> 	13  NDB.Covid19.iOS.AppleAPI            0x000000010138e770 NDB.Covid19.iOS.AppleAPI + 3925872
> 	14  NDB.Covid19.iOS.AppleAPI            0x00000001025c0f80 mono_pmip + 28148
> 	15  NDB.Covid19.iOS.AppleAPI            0x000000010267c45c mono_pmip + 795344
> 	16  NDB.Covid19.iOS.AppleAPI            0x000000010267fcc0 mono_pmip + 809780
> 	17  NDB.Covid19.iOS.AppleAPI            0x0000000100fd54c0 NDB.Covid19.iOS.AppleAPI + 21696
> 	18  NDB.Covid19.iOS.AppleAPI            0x0000000100fdf230 NDB.Covid19.iOS.AppleAPI + 62000
> 	19  Foundation                          0x00000001bd662f78 C82F8A4F-3D0F-33DB-8D40-C1E8BEF27E56 + 1273720
> 	20  CoreFoundation                      0x00000001bd1f6c18 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 691224
> 	21  CoreFoundation                      0x00000001bd1f6b70 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 691056
> 	22  CoreFoundation                      0x00000001bd1f62f8 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 688888
> 	23  CoreFoundation                      0x00000001bd1f1328 50CF3336-313F-3A7D-9048-CB1ED8EC3368 + 668456
> 	24  CoreFoundation                      0x00000001bd1f0ce8 CFRunLoopRunSpecific + 424
> 	25  GraphicsServices                    0x00000001c733b38c GSEventRunModal + 160
> 	26  UIKitCore                           0x00000001c131f444 UIApplicationMain + 1932
> 	27  NDB.Covid19.iOS.AppleAPI            0x00000001014b9118 NDB.Covid19.iOS.AppleAPI + 5148952
> 	28  NDB.Covid19.iOS.AppleAPI            0x0000000101458bc0 NDB.Covid19.iOS.AppleAPI + 4754368
> 	29  NDB.Covid19.iOS.AppleAPI            0x0000000101458b44 NDB.Covid19.iOS.AppleAPI + 4754244
> 	30  NDB.Covid19.iOS.AppleAPI            0x0000000100ff2c04 NDB.Covid19.iOS.AppleAPI + 142340
> 	31  NDB.Covid19.iOS.AppleAPI            0x000000010138e770 NDB.Covid19.iOS.AppleAPI + 3925872
> 	32  NDB.Covid19.iOS.AppleAPI            0x00000001025c0f80 mono_pmip + 28148
> 	33  NDB.Covid19.iOS.AppleAPI            0x000000010267c45c mono_pmip + 795344
> 	34  NDB.Covid19.iOS.AppleAPI            0x00000001026826b4 mono_pmip + 820520
> 	35  NDB.Covid19.iOS.AppleAPI            0x000000010259f538 NDB.Covid19.iOS.AppleAPI + 22869304
> 	36  NDB.Covid19.iOS.AppleAPI            0x000000010275f020 _Z9__isctypeim + 62652
> 	37  NDB.Covid19.iOS.AppleAPI            0x0000000100febf84 NDB.Covid19.iOS.AppleAPI + 114564
> 	38  libdyld.dylib                       0x00000001bd0788f0 90BD401C-9E8F-354E-A74F-D4C152DEB1D8 + 6384
> ```

Could any of you help us, any help is tremendously appreciated!

**Comment by havart-netcompany** [comment]
I hope this is a bug directly in the ExposureNotification code. I'll look at this a little bit now. If anybody has some suspicions or has managed to avoid this error already, please let me know

**Comment by mattleibow** [comment]
Not verified at this point, but it might be because of this:

https://github.com/xamarin/xamarin.exposurenotification/blob/fb7d888ebce17ab7d579a7c51c3e9ff30688502d/Xamarin.ExposureNotification/ExposureNotification.ios.cs#L53-L54

Going to change it to always set the metadata property... especially with `__NSFrozenDictionaryM`

**Comment by Redth** [comment]
I don't think the Android crash you are seeing is related to the configuration at all.

The stack trace looks like it's coming from submitting the key files to the native API.  The error seems rather clear that there's something invalid in the key files being generated on the server.

**Comment by havart-netcompany** [comment]
I believe you're right, Red. We are able to ProvideDiagnosisKeysAsync on Android without errors now

**Comment by TMHolen95** [comment]
I think there are two different errors here - I checked updating the NSDictonary to this:
`var nsArr = NSArray.FromObjects(2, c.DurationAtAttenuationThresholds[0], c.DurationAtAttenuationThresholds[1]);`
`nc.Metadata ??= new NSDictionary(
					new NSString("attenuationDurationThresholds"), nsArr
				);`

It appears to work and yields a new stack trace though, which do appear to indicate something is wrong with our files on iOS as well:

> Foundation.NSErrorException: Error Domain=ENErrorDomain Code=15 "(null)" UserInfo={cuErrorMsg=File identifier mismatch}
>   at Xamarin.ExposureNotifications.ExposureNotification.PlatformDetectExposuresAsync (System.Collections.Generic.IEnumerable`1[T] keyFiles, System.Threading.CancellationToken cancellationToken) [0x0016f] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.ios.cs:161
>   at Xamarin.ExposureNotifications.ExposureNotification+<>c__DisplayClass13_0.<UpdateKeysFromServer>b__0 (System.Collections.Generic.IEnumerable`1[T] downloadedFiles) [0x001d0] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:108
>   at NDB.Covid19.Base.AppleGoogle.ExposureNotification.ExposureNotificationHandler.FetchExposureKeyBatchFilesFromServerAsync (System.Func`2[T,TResult] submitBatches, System.Threading.CancellationToken cancellationToken) [0x00747] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ExposureNotification/ExposureNotificationHandler.cs:211
>   at Xamarin.ExposureNotifications.ExposureNotification.UpdateKeysFromServer (System.Threading.CancellationToken cancellationToken) [0x0006d] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/Xamarin.ExposureNotification/ExposureNotification.shared.cs:88
>   at NDB.Covid19.Base.AppleGoogle.ViewModels.ENDeveloperToolsViewModel.PullKeysFromServer () [0x0003b] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.Base.AppleGoogle/ViewModels/ENDeveloperToolsViewModel.cs:135
>   at NDB.Covid19.iOS.AppleAPI.ENDeveloperToolsViewController+<ENDevPullKeys_TouchUpInside>d__63.MoveNext () [0x00025] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.iOS.AppleAPI/Views/ENDeveloperTools/ENDeveloperToolsViewController.cs:51
>   at NDB.Covid19.iOS.AppleAPI.Application.Main (System.String[] args) [0x00022] in /Users/tormah/Desktop/Covid/Covid2/NDB_corona_app/NDB.Covid19/NDB.Covid19.iOS.AppleAPI/Main.cs:21
