### ISSUE TITLE
Native API implementation (Android)

### ISSUE THREAD

**Issue by kazumihirose** [xamarin/xamarin.exposurenotification#7]
Implementation sample has been released.
https://github.com/google/exposure-notifications-android

**Comment by Redth** [comment]
Thanks, we have now released bindings  https://www.nuget.org/packages/Xamarin.GooglePlayServices.Nearby.ExposureNotification/18.0.2-eap.2

And our cross platform API has been updated to use these bindings.  We will be releasing a preview nuget package of our cross platform API today as well.
