### ISSUE TITLE
Risk scores are 0 on Android

### ISSUE THREAD

**Issue by havart-netcompany** [xamarin/xamarin.exposurenotification#79]
I think there is a problem with risk scores on Android. When ExposureNotificationHandler.ExposureDetectedAsync runs, I get a summary with matchedKeyCount 10, but all risk scores are 0. If I run getExposureInfo, I get a bunch of ExposureInfo objects with risk score 0. Doing the same on iOS, gives ExposureDetectionSummary and ExposureInfo objects with risk scores > 0.

Breakpoint here:
![image](https://user-images.githubusercontent.com/65737062/84291314-3516c800-ab45-11ea-9605-08fecafe6011.png)

This is the summary object in Locals:
![image](https://user-images.githubusercontent.com/65737062/84291331-3ba53f80-ab45-11ea-93f9-bcb71e3e265c.png)

The screenshots are for 0.7.0, but it's the same problem on 0.8.0

**Comment by havart-netcompany** [comment]
I think the 0 scores were because of the Configuration we were using. I changed to a default configuration, just with maxed out duration scores and min risk score 1, and was able to get:
![image](https://user-images.githubusercontent.com/65737062/84365187-61782600-abd1-11ea-83e4-6e615ad6e9cb.png)
![image](https://user-images.githubusercontent.com/65737062/84365232-72c13280-abd1-11ea-9a6f-3464c767e9c8.png)
I'll try to see if we can get rid of the anomalies we are seeing by adjusting the Configuration

**Comment by havart-netcompany** [comment]
It is still unkown how we were able to record this anomaly, though:
![image](https://user-images.githubusercontent.com/65737062/84368673-27f5e980-abd6-11ea-89c0-7592963b1e06.png)
1 matched key, MaximumRiskScore 64, SummationRiskScore 320. Do you suspect that this is a bug in Play Services @mattleibow ?

**Comment by havart-netcompany** [comment]
**I did 4 experiments** with with breakpoints here:
- The first line of ExposureNotificationHandler.ExposureDetectedAsync()
- The first line after getting out the IEnumerable\<ExposureInfo> with the getExposureInfo() parameter of ExposureNotificationHandler.ExposureDetectedAsync()

**My current conclusion:** On Android, the only thing Configuration.MinimumRiskScore does is to tell the EN API "if an exposure incident has TotalRiskScore less than MinimumRiskScore, then set TotalRiskScore to 0, but otherwise treat it exactly the same as other exposure incidents". On iOS, Configuration.MinimumRiskScore doesn't do anything.

The differences I observed between iOS and Android could just be because the EN API is different on each platform, or maybe the MinimumRiskScore is not provided correctly in the iOS part of Xamarin.ExposureNotification.

**Experiment 1: Running on Android. Using a Configuration with the default values, except that we set Configuration.MinimumRiskScore to 4096**
At the first breakpoint, Locals shows us this ExposureDetectionSummary:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/65737062/84425557-13d7d980-ac22-11ea-9637-4ae272545e5a.png">
At the second breakpoint, Locals shows us this IEnumerable\<ExposureInfo>:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/65737062/84425605-2a7e3080-ac22-11ea-9cd6-7611d109080b.png">

**Experiment 2: Running on Android. Using a Configuration with the default values, except that we set Configuration.MinimumRiskScore to 1**
ExposureDetectionSummary:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/65737062/84425859-83e65f80-ac22-11ea-8549-d66dea70ff17.png">
IEnumerable\<ExposureInfo>:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/65737062/84425882-9791c600-ac22-11ea-84a2-2e2d16694317.png">

**Experiment 3: Running on iOS. Using a Configuration with the default values, except that we set Configuration.MinimumRiskScore to 4096**
<img width="697" alt="image" src="https://user-images.githubusercontent.com/65737062/84427850-dbd29580-ac25-11ea-9f2a-391e38139d3b.png">
IEnumerable\<ExposureInfo>:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/65737062/84427899-e7be5780-ac25-11ea-99ea-0669d4a1f3ea.png">

**Experiment 4: Running on iOS. Using a Configuration with the default values, except that we set Configuration.MinimumRiskScore to 1**
ExposureDetectionSummary:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/65737062/84427619-81d1d000-ac25-11ea-9ba4-312aade284e6.png">
IEnumerable\<ExposureInfo>:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/65737062/84427679-92824600-ac25-11ea-9aeb-38f88647a44a.png">

**Comment by mattleibow** [comment]
There is a new xcode beta out... you could see what ios did there...

**Comment by havart-netcompany** [comment]
Oh no... iOS minimum risk score is also capped at 255. I saw this thing at the documentation for minimum risk score: 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/65737062/84430574-2b1ac500-ac2a-11ea-933b-196ad1be6db5.png">
So I think we need a nice fix like this one: https://github.com/xamarin/xamarin.exposurenotification/issues/81

**Comment by havart-netcompany** [comment]
**My new current conclusion**: iOS exposure incidents with risk score below the threshold are actually ignored except that they count towards "matched key count", while on Android, it's just the risk score in an exposure incident below the threshold that gets ignored. This is probably not a problem in Xamarin.ExposureNotification

**Experiment 5:** Running on iOS. Using a Configuration with AttenuationScores, AttenuationScores, DurationScores, TransmissionRiskScores all being integer arrays containing {2,2,2,2,2,2,2,2}, and with minimum risk score 255.
ExposureDetectionSummary:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/65737062/84437291-0841de00-ac35-11ea-88cf-726424d2ddae.png">
IEnumerable\<ExposureInfo>:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/65737062/84436465-ca908580-ac33-11ea-93fa-ca1a103f632e.png">

**Experiment 6**: Same as experiment 5, but minimum risk score = 1.
ExposureDetectionSummary:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/65737062/84436816-53a7bc80-ac34-11ea-8cac-c46d9ced83d4.png">
IEnumerable\<ExposureInfo>:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/65737062/84436878-6ae6aa00-ac34-11ea-92a1-16c158c9624b.png">
