### ISSUE TITLE
Main Branch?

### ISSUE THREAD

**Issue by dlandi** [xamarin/xamarin.exposurenotification#80]
I noticed the addition of a "Main" Branch. And I saw some comments on twitter from the team. So which is the primary branc? "Main" or "Master"?

**Comment by mattleibow** [comment]
There is only 1 branch: `main`.

Master was renamed for this repo.

**Comment by dlandi** [comment]
OK. Thanks for clarifying. I see both branches in my VS Studio Github Extension.

**Comment by mattleibow** [comment]
Ah, that might be just your local version. I just checked out main and then deleted master for my repos. Some people use scripts and do all fancy things :)
