### ISSUE TITLE
Get ENExposureInfo.totalRiskScoreFullRange on iOS

### ISSUE THREAD

**Issue by havart-netcompany** [xamarin/xamarin.exposurenotification#81]
On iOS, ExposureInfo.TotalRiskScore is capped at 255, but there exists an uncapped value according to the documentation: https://developer.apple.com/documentation/exposurenotification/enexposureinfo. Maybe a fix like ExposureDetectionSummary.HighestRiskScore would be useful

**Comment by mattleibow** [comment]
Just a link for reference https://github.com/xamarin/xamarin.exposurenotification/issues/73

**Comment by mattleibow** [comment]
I'll have a look.

**Comment by mattleibow** [comment]
@havart-netcompany I have a PR here: https://github.com/xamarin/XamarinComponents/pull/900

Once it is built, I'll attach it here and you can test it. The reason I don't want to push to nuget just yet is that the docs say nothing about the values in the info. I do know that there is a new property in the new beta of iOS, but we can't make users do that. So, maybe it will be in the metadata.

**Comment by mattleibow** [comment]
Actually, it says "Not used." in the docs... I wonder what will happen...

https://developer.apple.com/documentation/exposurenotification/enexposuredetectionsummary/3586324-metadata?language=objc

**Comment by mattleibow** [comment]
Here is the nupkg... Let me know if that property lights up with great things.

Seems GitHub does not allow attaching of files with a .nupkg extension, so I zipped it up :)

[Xamarin.ExposureNotification.0.10.0-alpha.nupkg.zip](https://github.com/xamarin/xamarin.exposurenotification/files/4764399/Xamarin.ExposureNotification.0.10.0-alpha.nupkg.zip)

**Comment by TMHolen95** [comment]
It seems like it's working when I use the 0.10.0 nupkg 
![image](https://user-images.githubusercontent.com/11331332/84396959-cbf38b00-abfe-11ea-88aa-ec640a12613a.png)

**Comment by mattleibow** [comment]
SWEET! I'll merge and push!

**Comment by mattleibow** [comment]
Now on NuGet! https://www.nuget.org/packages/Xamarin.ExposureNotification/0.10.0-preview
